name: nuget publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Install dependencies
      run: dotnet restore ETWC.sln
    - name: Build
      run: dotnet build ETWC.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ExpressionToWhereClause.Test/ExpressionToWhereClause.Test.csproj --no-restore --verbosity normal
      
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.2.1
      with:
        PROJECT_FILE_PATH: ExpressionToWhereClause/ExpressionToWhereClause.csproj
        TAG_COMMIT: true
        VERSION_FILE_PATH: ExpressionToWhereClause/ExpressionToWhereClause.csproj
        VERSION_REGEX: <Version>(.*)<\/Version>
        NUGET_KEY: ${{ secrets.NugetKey }} 

